// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8X3zLTUVJujPQcaeyHITFVlStgtjIp4w',
    appId: '1:572833526564:web:a323ecd8a62581d03c79b1',
    messagingSenderId: '572833526564',
    projectId: 'lifeos-4ab3f',
    authDomain: 'lifeos-4ab3f.firebaseapp.com',
    storageBucket: 'lifeos-4ab3f.firebasestorage.app',
    measurementId: 'G-ME9HWKNE5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqTgf72ELZ2r5KyNMYyq4suDvItDvIcJE',
    appId: '1:572833526564:android:991da65f95ccb4503c79b1',
    messagingSenderId: '572833526564',
    projectId: 'lifeos-4ab3f',
    storageBucket: 'lifeos-4ab3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHdnlDSduDcoV356mMZ2vr2QrlFSAJhiQ',
    appId: '1:572833526564:ios:1492428d5d9ddd883c79b1',
    messagingSenderId: '572833526564',
    projectId: 'lifeos-4ab3f',
    storageBucket: 'lifeos-4ab3f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHdnlDSduDcoV356mMZ2vr2QrlFSAJhiQ',
    appId: '1:572833526564:ios:1492428d5d9ddd883c79b1',
    messagingSenderId: '572833526564',
    projectId: 'lifeos-4ab3f',
    storageBucket: 'lifeos-4ab3f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8X3zLTUVJujPQcaeyHITFVlStgtjIp4w',
    appId: '1:572833526564:web:f9387a477d6ee5903c79b1',
    messagingSenderId: '572833526564',
    projectId: 'lifeos-4ab3f',
    authDomain: 'lifeos-4ab3f.firebaseapp.com',
    storageBucket: 'lifeos-4ab3f.firebasestorage.app',
    measurementId: 'G-3EDH2ZWYMH',
  );
}
